app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as'=>'home','uses'=>'JobController@index'));

Route::get('user/logout', array('as'=>'user.logout', 'uses' => 'UserController@logout'));

Route::post('user/login', array('as'=>'user.login', 'uses' =>'UserController@login'));

Route::post('job/search', array('as'=>'job.search', 'uses' =>'JobController@search'));

Route::resource('job', 'JobController');
Route::resource('user', 'UserController');
Route::resource('application', 'ApplicationController');

app/models/Job.php
<?php 
class Job extends Eloquent
{ //Creates rules for job creation form
  public static $rules = array(
  'title' => 'required',
  'description' => 'required',
  'location' => 'required',
  'salary' => 'required:min:0'
  );
  
 //creates one to many relationship to user table
 function user()
 {
 return $this->belongsTo('User');
 }

  //creates one to many relationship to user table
 function applications()
 {
 return $this->hasMany('Application');
 }
  
}

?>

app/controllers/JobController.php
<?php

class JobController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
  
  //shows index of jobs paginated by 4 and ordered by the creation date
	public function index()
	{
    $jobs = Job::orderBy('created_at', 'desc')->paginate(4);
    return View::make('jobs.index')->with('jobs',$jobs);
    
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
  
  //Allows logged in employer users to add jobs
	public function create()
	{
    if (!Auth::check()) return Redirect::route('job.index');
		return View::make('jobs.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
  
  //Allows logged in employer users to store added jobs
	public function store()
	{
    if (!Auth::check()) return Redirect::route('job.index');
		$input = Input::all();
    $v = Validator::make($input, Job::$rules);
    if ($v->passes())
    
    {
    $job = new Job();
    $job->user_id = Auth::user()->id;
    $job->title = $input['title'];
    $job->description = $input['description'];
    $job->location = $input['location'];
    $job->salary = $input['salary'];
    $job->updated_at;
    $job->save();
    return Redirect::route('job.show', $job->id);
    }
    
    else {
      return Redirect::route('job.create')->withErrors($v);
    }
    
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  
  //Shows job description for users 
	public function show($id)
	{ if (!Auth::check()) return Redirect::route('job.index');
   else {
		$job = Job::find($id);
    return View::make('jobs.show', compact('job'));
    }
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  
  //Allows employer users to edit job description
	public function edit($id)
	{
    if (!Auth::check()) return Redirect::route('job.index');
		$job = Job::find($id);
    return View::make('jobs.edit')->with('job', $job);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  
  //Updates the job description
	public function update($id)
	{ 
    if (!Auth::check()) return Redirect::route('job.index');
    
		$job = Job::find($id);
    
    $input = Input::all();
    
    $job->title = $input['title'];
    $job->description = $input['description'];
    $job->location = $input['location'];
    $job->salary = $input['salary'];
    $job->save();
    return Redirect::route('job.show', $job->id);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  
  //Destroys selected job if employer user
	public function destroy($id)
	{
    if (!Auth::check()) return Redirect::route('job.show');
		$job = Job::find($id);
    $job->delete();
    return Redirect::route('job.index');
	}
  
  //Allows job seekers to search via keywords *currently does not work
  public function search()
    {
    $keyword= Input::get('keyword');
    
    $jobs = Job::where('title', 'LIKE', '%'.$keyword.'%')->get();
    
    return Redirect::route('job.index');
    }
  
}

app/views/jobs/create.blade.php
@extends('layout')
@section('title')
Add Job
@stop 
@section('column2')
      <h1> Add Job</h1>
      {{ Form::open(array('action' =>   'JobController@store')) }}
            {{ Form::label('title', 'Job Title: ') }}
            {{ Form::text('title', null, array('class'=>'form-control')) }}
            {{ $errors->first('title') }}
  
            {{ Form::label('description', 'Description: ') }}
            {{ Form::text('description', null, array('class'=>'form-control')) }}
            {{ $errors->first('description') }}
  
            {{ Form::label('location', 'Location: ') }}
            {{ Form::text('location', null, array('class'=>'form-control')) }} 
            {{ $errors->first('location') }}
  
            {{ Form::label('salary', 'Salary: ') }}
            {{ Form::text('salary', null, array('class'=>'form-control')) }}
            {{ $errors->first('salary') }}
            <br/>
            {{ Form::submit('Create', array('class'=>'btn btn-default')) }}

      {{ Form::close() }}

@overwrite

app/views/jobs/edit.blade.php
@extends('layout')
@section('title')
Edit Job
@stop
@section('column2')
        {{ Form::model($job, array('method'=>'PATCH', 'route'=> array('job.update', $job->id))) }}

        {{ Form::label('title', 'Job Title: ') }}  
        {{ Form::text('title', null, array('class'=>'form-control')) }}
 
        {{ Form::label('description', 'Description: ') }}
        {{ Form::text('description', null, array('class'=>'form-control')) }}
  
        {{ Form::label('location', 'Location: ') }}
        {{ Form::text('location', null, array('class'=>'form-control')) }} 

        {{ Form::label('salary', 'Salary: ') }}
        {{ Form::text('salary', null, array('class'=>'form-control')) }}
        <br/>
        {{ Form::submit('Update', array('class'=>'btn btn-default')) }}
        {{ Form::close() }}

@overwrite

app/views/jobs/index.blade.php
@extends('layout')
@section('title')
Jobs
@stop

@section('column1')
@if (Auth::check()) 
    <div class="list-group">
      <img src="{{ Auth::user()->image->url('thumb') }}">
        @if (Auth::user()->category=='employer')
            <a href="job/create" class="list-group-item">Add Job</a>
            <a href="application/index" class="list-group-item">View Applications</a>
        @endif
    </div>
@endif
@overwrite

@section('column2')
    @if (Auth::check())
        <h1>Job List</h1>
            {{ Form::open(array('url'=>'job.search')) }}
              
            {{ Form::text('keyword', null, array('class'=>'form-control','placeholder'=>'search by keyword e.g title, location, salary, description')) }}
            <br/>
            {{Form::submit('search' , array('class'=>'btn btn-default'))}}
            {{Form::close() }}
        <br/>
        <ul>
            
            @foreach ($jobs as $job)
            @if ($job->id == Auth::user()->id)
                <li> {{link_to_route('job.show', $job->title, array($job->id)) }}</li>
           @endif
           @endforeach
           
          @foreach ($jobs as $job)
            @if (Auth::user()->category == 'jobseeker')
          <li> {{link_to_route('job.show', $job->title, array($job->id)) }}</li>
            @endif
          @endforeach
        </ul>

        {{ $jobs->links() }}

    @else
        <p>We help connect employers across Australia with the experienced and knowledgable staff that they need. With thousands of jobs being offered we're sure you'll find a career that suits you</p>
    @endif
@overwrite

app/views/jobs/show.blade.php
@extends('layout')
@section('title')
Job Details
@stop
@section('column1')
        <div class="list-group">
            @if (Auth::check()) 
                <a href="{{route('job.index')}}" class="list-group-item">Back to Jobs</a>
            @endif
        </div>
@overwrite

@section('column2')
            <h1> Job Details</h1>

            <p> Employer Id: {{{$job->user_id}}}
            <p> Title: {{{$job->title}}} </p>
            <p> Description: {{{$job->description}}}</p>
            <p> Location: {{{$job->location}}}</p>
            <p> Salary: {{{$job->salary}}}</p>
            <p> Posted At: {{{$job->created_at}}}</p>
            <p> Last Updated: {{{$job->updated_at}}}</p>
            @if (Auth::user()->category == 'jobseeker')
            <p> {{link_to_route('application.create', 'Apply', $applcation = array($job->id)) }} </p>
            @else
            <p> {{link_to_route('job.edit', 'Edit', array($job->id)) }} </p>

            {{ Form::open(array('method' => 'DELETE', 'route'=>array('job.destroy', $job->id))) }}
            {{ Form::submit('Delete', array('class'=>'btn btn-danger')) }}
            {{Form::close()}}
@endif
@overwrite