app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as'=>'home','uses'=>'JobController@index'));

Route::get('user/logout', array('as'=>'user.logout', 'uses' => 'UserController@logout'));

Route::post('user/login', array('as'=>'user.login', 'uses' =>'UserController@login'));

Route::post('job/search', array('as'=>'job.search', 'uses' =>'JobController@search'));

Route::resource('job', 'JobController');
Route::resource('user', 'UserController');
Route::resource('application', 'ApplicationController');

app/models/Application.php
<?php 
class Application extends Eloquent
{ //Creates rules for appication form
  public static $rules = array(
  'letter' => 'required',
  'applicant' => 'required'
  );

 //Creates many to many relationship with users
 function user()
 {
 return $this->belongsToMany('User');
 }
  
 //Creates many to many relationship with jobs
 function job()
 {
 return $this->belongsToMany('Job');
 }

}

?>

app/controllers/ApplicationController.php
<?php

class ApplicationController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
  
  //returns 2 paginated applications per pagination page
	public function index()
	{
		$applications = Application::paginate(2);
    return View::make('application.index', compact('applications'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
  
  //creates link to application create.blade.php
	public function create()
	{
		return View::make('application.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
  
  //Stores input data for application
	public function store()
	{
		$input = Input::all();
    $v = Validator::make($input, Application::$rules);
    if ($v->passes())
    
    {
    $application = new Application();
    $application->user_id = Auth::user()->id;
    $application->job_id = Job::find($job->id);
    $application->applicant = $input['applicant'];
    $application->letter = $input['letter'];
    $application->save();
    return Redirect::route('application.show', $application->id);
    }
    
    else {
      return Redirect::route('application.create')->withErrors($v);
    }
    
	}
  
  
	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  
  //Creates link to show.blade.php in application folder and displays application details
	public function show($id)
	{
	  $application = Application::find($id);
    return View::make('application.show', compact('application'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/application/create.blade.php
@extends('layout')
@section('title')
Apply
@stop 
@section('column2')
      {{ Form::open(array('action' => 'ApplicationController@store')) }}
            {{ Form::label('applicant', 'Applicant name: ') }}
            {{ Form::text('applicant', null, array('class'=>'form-control')) }}
            {{ $errors->first('applicant') }}

            {{ Form::label('letter', 'Application letter: ') }}
            {{ Form::text('letter', null, array('class'=>'form-control')) }}
            {{ $errors->first('letter') }}
            <br/>
            {{ Form::submit('Apply', array('class'=>'btn btn-default')) }}
      {{ Form::close() }}

@overwrite

app/views/application/index.blade.php
@extends('layout')
@section('title')
Applications
@stop
@section('content')

<ul>
  @foreach ($applications as $application)
  <li> {{link_to_route('application.show', $application->id, array($application->id)) }}</li>
  @endforeach
  
</ul>

{{ $application->links() }}


@overwrite

app/views/application/show.blade.php
@extends('layout')
@section('title')
Apply Summary
@stop
@section('column1')
        <div class="list-group">
            @if (Auth::check())
                <a href="{{route('job.index')}}" class="list-group-item">Back to Jobs</a>
            @endif
        </div>
@overwrite

@section('column2')
      <h1> Application </h1>
      <br/>
      Applicant Id: {{{$application->user_id}}}<br/>
      Job Id: {{{$application->job_id}}}<br/>
      Applicant Name: {{{$application->applicant}}} <br/>
      Application Letter: {{{$application->letter}}} <br/>
      Applied at: {{{$application->created_at}}}

@overwrite